name = "قياسي"
client_id = ""

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://qiyasi.net/api/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
