name            = "قياسي"
client_id       = "d9645bc5d285e2a0464fbd0a8ad28e75"
application_url = "https://qiyasi.net/dashboard"
embedded        = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://qiyasi.net/api/shopify/callback"
]

[webhooks]
api_version = "2024-01"
